@apiUrl = http://localhost:4000

GET {{apiUrl}}/videos

###

POST {{apiUrl}}/videos
Content-Type: application/json

{
  "title": "Putas cojiendo Rico",
  "url": "https://www.xvideos.com/video45045325/c._putas_cogiendo_rico",
  "description": "sexo duro con unas perras rabiosa"
}

### GET VIDEO
GET {{apiUrl}}/videos/601f97d2b5e2f52ad052d05a

### DELETE VIDEO
DELETE {{apiUrl}}/videos/601f734fdc459323307c6fc3

### UPDATE
PUT {{apiUrl}}/videos/601f97d2b5e2f52ad052d05a
Content-Type: application/json

{
  "title": "Putas cojiendo sabroso"
}